name: mocci
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.9.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  carousel_slider: 4.0.0
  get_storage: 2.0.3
  double_back_to_close: 2.0.0
  english_words: 4.0.0
  cached_network_image: ^3.1.0
  pin_code_fields: 7.3.0
  flutter_svg: 0.22.0
  image_picker: 0.8.4
  flutter_screenutil: 5.0.0+2
  google_fonts: 2.1.0
  flutter_spinkit: 5.0.0
  dio: 4.0.0
  infinite_scroll_pagination: 3.1.0
  font_awesome_flutter: 9.1.0
  flutter_credit_card: 2.0.0
  package_info: 2.0.2
  equatable: 2.0.3
  smooth_page_indicator: ^1.0.0+2
  dots_indicator: ^2.0.0
  flutter_html: 2.1.4
  pull_to_refresh: 2.0.0
  webview_flutter: 2.1.1
  chips_choice: 2.0.1
  flutter: 
    sdk: flutter
  flutter_staggered_animations: ^1.0.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Carmen Sans
      fonts: 
        - asset: assets/fonts/Carmen Sans Medium.otf
        - asset: assets/fonts/Carmen Sans Regular.otf
        - asset: assets/fonts/Carmen Sans SemiBold.otf
  uses-material-design: true

